version: '3'
services:
  app:
    build: .
    environment:
      - BOT_TOKEN=$BOT_TOKEN
    depends_on:
      - mongo
    networks:
      - bot-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - bot-network

networks:
  bot-network:
